name: Development -> Push Flexcore Backend to GCP

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=core_development
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
            -Dsonar.qualitygate.wait=true
      
      - name: Docker Build
        uses: flextock/actions-docker-gcr/build@v1.1
        with:
          image: test-dotnetcore-342113/core-dev

      - name: Docker Push
        
        uses: flextock/actions-docker-gcr/push@v1.1
        with:
          image: test-dotnetcore-342113/core-dev
          gcloud_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '310.0.0'
          service_account_key: ${{ secrets.GCLOUD_DEPLOY_RUN }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy core-dev --quiet --image gcr.io/test-dotnetcore-342113/core-dev:latest --project test-dotnetcore-342113 --region us-central1 --platform managed
      
